# Generated by Django 5.1.1 on 2024-10-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_delivery_details_pet_alter_payments_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_details',
            name='delivery_token',
            field=models.IntegerField(),
        ),
    ]
